services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - PGDATA:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    expose:
      - '5432'
  odoo:
    image: odoo:16.0
    restart: always
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      DB_HOST: db
      DB_PORT: '5432'
      DB_USER: odoo
      DB_PASSWORD: odoo
      DB_NAME: odoo

volumes:
  odoo_log:
  PGDATA:
  odoo_data: