services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - pgdata=/var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    expose:
      - '5432'

  odoo:
    image: odoo:16.0
    restart: always
    depends_on:
      - db
    ports:
      - '8069:8069'
    tty: true
    command: -- --dev=reload
    # command: odoo scaffold module_technical_name /mnt/extra-addons
    volumes:
      - ./odoo/addons:/mnt/extra-addons
      - ./odoo/config:/etc/odoo
      - odoo_data:/var/lib/odoo
      - odoo_log:/var/log/odoo
volumes:
  pgdata:
  odoo_log:
  odoo_data: